conda create -y -n RAG_env_conda ; 
conda activate RAG_env_conda ; 
conda install -y -c conda-forge python=3.10 ; 
conda install -y pip ; 
[path to conda installation]/envs/RAG_env_conda/bin/pip install ragatouille==0.0.7.post9 ; 
[path to conda installation]/envs/RAG_env_conda/bin/pip uninstall -y faiss-cpu ; 
[path to conda installation]/RAG_env_conda/bin/pip uninstall -y faiss ; 
conda install -y matplotlib==3.8.4 ;
conda install -y -c conda-forge faiss-gpu==1.7.4 ;
conda install -y ninja ;